name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    shell: pwsh

jobs:
  build-and-test:
    name: build-and-test on ${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v6
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        global-json-file: global.json
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -p:ContinuousIntegrationBuild=True -p:ReleaseDateAttribute=True --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal --logger trx --results-directory ${{ runner.temp }}
    - name: Convert TRX to VS Playlist
      if: failure()
      uses: BenjaminMichaelis/trx-to-vsplaylist@v3
      with:
        trx-file-path: '${{ runner.temp }}/*.trx'
        output-directory: '${{ runner.temp }}/vsplaylists'

  aot-test:
    name: AOT publish test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        global-json-file: global.json
    - name: Install NativeAOT prerequisites
      run: sudo apt-get install -y clang zlib1g-dev
    - name: Publish AOT
      run: dotnet publish IntelliTect.Multitool.AotTest/IntelliTect.Multitool.AotTest.csproj -r linux-x64 -c Release
    - name: Run AOT binary
      run: ./IntelliTect.Multitool.AotTest/bin/Release/net8.0/linux-x64/publish/IntelliTect.Multitool.AotTest

  automerge:
    needs: [build-and-test]
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: fastify/github-action-merge-dependabot@v3.12.0  
